exports.baseUrl = "https://api.samplicio.us/Supply/v1/Surveys/AllOfferwall";
exports.supplierCode = 6413;
exports.collectsPII= 0;
exports.CPIGTE =0.80;
exports.CPILTE=5;
exports.overallCompletesGTE=25;
exports.surveyQuotaCalcTypeID=1;
exports.conversionGTE=15;
exports.bidLengthOfInterviewLTE=20;
exports.BidIncidenceGTE= 25;
exports.VendorIdForMapping = ['2420212VENDOR1616592262014'];
exports.ApiClientId = 10;
exports.surveyQualUrl = "https://api.samplicioo.us/Supply/v1/SurveyQualifications/BySurveyNumberForOfferwall/";
exports.Authorization =  'C9D1462F-42DC-46A6-B9C4-C883B7F8032E'
exports.QuotaUrl = "https://api.samplicioo.us/Supply/v1/SurveyQuotas/BySurveyNumber/";
exports.groupSurveyUrl ="https://api.samplicio.us/Supply/v1/Surveys/SurveyGroups/BySurveyNumber/";
exports.PURE_BASE_URL = "https://api.spectrumsurveys.com/buyers/v2/",
exports.PURE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZTk4ZmE0MjMxY2VjMGQwZGE3ZmUzZCIsInVzcl9pZCI6Ijk3MjYiLCJpYXQiOjE2NDI2OTY2MTJ9.C4F4eE9UuY0UbsYC26yaJMBQ-Lti33AU1KmA-Wxf_kY",
exports.PURE_CREATESURVEY = "surveys"