// ALL CONSTANTS
module.exports = Object.freeze({
    MANUAL_CREATED_SURVEY_TYPE_ID: 0,
    MCQ_SURVEY_TYPE_ID: 1,
    PTWOSAMPLE_SURVEY_TYPE_ID: 2,
    PRECISION_SURVEY_TYPE_ID: 3,
    DYNATA_SURVEY_TYPE_ID: 7,
    IPSOS_SURVEY_TYPE_ID: 17,
    Unimrkt_SURVEY_TYPE_ID: 24,
    Elicit_SURVEY_TYPE_ID: 26,
    INNOVATE_SURVEY_TYPE_ID: 25,
    CATALYSE_CLIENT_TYPE_ID: 30
});