exports.buyerList1 = ["Corus","HLK Agency","Lorien Resourcing","McAllister Opinion Research","MZ HUB LLC","Probolsky Research - MP","Supercell Oy","Board of Innovation","Research Co.","Vypr Technologies LTD","Data Sciences","Pearson, S.A. de C.V.","Rare","Skift Inc.","PYMNTS","Researchify Pty Ltd","Cross Marketing Buyer","Inqvita AB","Public First Limited","The Seurat Group, LLC","ThinkSprint","VolKno","Face Facts Fieldwork Ltd","Novamex","Statista GmbH - CintX","Cint OX","Consumer Insights","dataSpring","Harry's, Inc.","Dynata","Linney Group","Outward Intelligence","Globis Gmbh","Lifetime Products Inc","Pacific Market Research","Wilkins Research Services","LA28","Borderless Access","Bovitz","Datamining Srl","Swayable","Syno Poland s.p. z o.o.","Meredith Operations Corporation","Walnut Unlimited","Potentia Insight Limited","Protobrand Sciences","Wahl Clipper Corporation","Rasmussen Reports","Data for Progress","Johnson And Lubbock Partners Limited","MARU Group","FremantleMedia Global","Honda Motor Co Ltd","Tobii","Technomic","WALR","NRC Health","Appinio","Canvas8","CRG","SmashBrand","The Bantam Group","Sense360","ROIRocket","Human Highway Milano","Dynata - REX Integration",
];

exports.buyerList2 = ["G5 Holdings Limited","Lumen Research","Intellectual Research Services","Zoho Corporation","Cortland Management, LLC","Lumini Interpretacion de Mercados","Nabu Group","Global Panel Research Solutions","SKIM Group","GfK","Decision Analyst","Decision Technology","Innovex Insight","Roth Capital Partners, LLC","Behavioural Insights LTD","Alligator Research","Woozle Research","Statista GmbH","TGM Research Pte.Ltd - CintX","Proof","Big Village Insights","Thinqinsight","Wizer",
];

exports.buyerList3 = ["Innovative Research Group","QuestionPro","Nspire","Hotspex","Abacus Data","AYTM","BSP Research","Fraym, Inc","Market Diggers","Catalyx","Mindmetriks Colombia s a s","Latitude","Radius Global","Data-Orchid","Cobalt Sky","HarrisX","Kantar_PE","Tapestry Research","Streetbees.com Limited","Instinct and Reason","Advise Research GmbH","Equation Research","Hauser & Associates, Inc.","InContext Solutions","Lab42","Wakefield","Collage Group","Robas Research","TrackOpinion","Human8","AYTM - Exchange Production","PureProfile Australia","Bolt Insight LTD","Virtual Store Trials","Harmon Research","Wasserman","Ugam","Civey GmbH","Split Second Research","Dumbstruck","JTN Research","Research Results, Inc.",
];

exports.buyerList4 = ["ISA","Futuresource","Dash Market Research","STRAT7","Melkart","Beta Hat Industries, LLC","Aeon Market Research","SurveyMonkey","OpinionRoute","Canadian Viewpoint","Omnisis Ltd","Dig Insights - Upsiide","EmotionTrac, Inc.","Precision","Knit","The Conversation Studio","Lucid Marketplace Services","Ipsos - SampleOne","Gauge Insights","Qualtrics","Interpret","Odyssey AB","Unimrkt Response API Cint Ex","Gazelle","Researchbods","Researchscape International","Research Lane","Sapio Research","Kantar","Drive Research, LLC",
];

exports.buyerList5 = ["Bespoke Market Intelligence","Precise Research Solutions PRSL","NULL","MMR Research World Wide","NuVooDoo Media Services LLC","Propeller Insights","Toluna","QuantifyAI","3Gem","Schnell Research","EyeSee","Morning Consult","SpeakNow","Unimrkt Response Inc Buyer","Intellisurvey","Savanta","Ovation Worldwide Holdings","Asia Research Partners","Explorer Research","Payswell, LLC","UserZoom","Quest Research Group","TGM Research Pte.Ltd","EMI","MSI ACI","Centiment","Qumind Ltd","Cloud Research","Rakuten Insight","Research at Glance","SurveySwap","Radma Research","Davis Research","Trayistats AI Technologies Pvt Ltd","Research Innovation and ROI","Main Frame Ltd.",
];

exports.buyerList6 = ["Survience Research and Consulting LLP","GMO Research","Research Clever Ltd","Conclave Market Research","Think Now Research","GeoPoll","Human Made Machine","B3 Intelligence","Far Post Media","TrendCandy","Azure Knowledge","TS AI","Rep Data - UI","Greenland Research","The Langston Co.","SAMPLINGFY MEXICANA","Pebbles And Sand Consulting","WiseWorks","Ipsos (Cint Exchange New)","Mercury Analytics","Macromill","Ipsos","Innovate MR","Bully Pulpit Interactive","Cint OTC","Norstat","CrossTab","CatalystMR","Eleven Inc.","Toluna IP","Opeepl ApS","Research Desk - Rep Data","Feedback Loop","Orchidea Research","MarketXcel","DC-Activ","Luth","Paradigm Sample","Candid Counsel","GrowthOps","MakerSights","Monet Networks","MobOpinions","Riva Research","Probity Research","ImpactSense","DataPull","Aulus Vision","Constant Contact","LogitGroup_CintX","THINK TANK Research","Prodege",
];

exports.buyerList7 = ["Alchemer LLC","Catalyse Research","Market Mirror Research Solutions","Internet Research Bureau","i360","Pureprofile","conjoint.ly","Catalyse Research - Cint Exchange","Echelon Insights","Culturati Research & Consulting","SMG (Service Management Group)","Opinaia","The Farnsworth Group Inc.","DataXing Digital","OpinionInn","QuestionLab","Global Opine Research LLC","Panel Viewpoint","Quid Insights","Global Consulting","Glmps Co.","RS Sample Junction","Internet Research Bureau - Cint Exchange","PROLOG INSIGHTS ZILLION MARKET PRIVATE LIMITED","KYA RESEARCH",
];

exports.buyerList8 = ["24seven Research Network","40DB. DATA S.L.","4Media Group Inc.","56 Degree Insight Ltd","Aces Digitale","Acsi","Action Market Research","Advent Insight Solutions","Advocates for Human Potential","Affluent Consumer Research","AGS GLOBAL Arastirma Danismanlik Ticaret A.S.","Aletheia Marketing & Media","Alternative Research Solutions S.a.","Angus Reid","Apsidata Solutions","ARKOPHARMA Laboratories","Atenga","Atheneum Partners LLC","Attest Technologies Limited","Audience API","Avalanche Strategy","Avni Tech Media LLC","Beaufort Research Limited","Behavio Labs","Benson Media Research Llc","BetterBody Foods","BIFI Berliner Institut für Innovationsforschung GmbH","BizRate","Blauw Research","Blue Owl AI","Bonning & Associates","Brainactive Pte Ltd - Cint Exchange","Branded Research","Bulbshare","C+R","Cars.Com","Cashew Corp","CBC/Radio-Canada","CDK Global, Inc.","Cint Commercial Demo","Cint Exchange Trial - GfK","Cint Marketing","Clarion MR","Climate200","CloudArmy","Cotton Incorporated","Cre'Online","Criteo","Crunched Analytics LLC","Cursory Technologies","Data Decipher Pvt. Ltd","Data Xcel","DATACTION OÜ","Datapraxis OU","Demo SCOPE AG - Adligenswil","Demos AU","Divergent Insights Buyer","Divergent Insights CintX","Dot Research SA de CV","DSCOVR srl","Dynamic Research","Eat Well Global, Inc","Edentify","Editorial Invesmarket Sl","Eklavya Analytics & Consulting Private Limited","Emazing Retailing",
    "Emerson College","empatiX Consulting","Encueston","Epic Conjoint","Epicenter Experience","eye square GmbH","Eyes4Research","Fases Broker Intelligence","FCB Chicago","Firmenich Cia Ltda","Flood & Partners Limited","FORWARD Insight and Strategy","Futurist Technologies","G.V.K. mbH","GEMBA Research","General Motors","Givaudan","Global Matrix Survey LLC","good-market.ing Ingenieurbüro für Marken","GroupSolver","Grow Progress","GS Strategy Group","GSSInsight","H3 Insights, LLC","Habit5 Limited","Harvard University","Harvey Consulting","Home Chef","horizoom","Hyper World","IFA Holdings","IgniteMR LLC","IncQuery","Innofact AG","Innoprobe Insight","INSA-CONSULERE","Insight For You","Instapanel","Intra Research OÜ","ION Media Networks,  Inc.","Ireland Thinks","IRL-GWS","Ironwood Insights","Isense Solutions SRL","Ivitaa Martech Solutions","Jasper Colin Research","Jeremy Tyler","Jockey International, Inc.","KFC Corporation","Kodiak Cakes","konversionsKRAFT (Web Arts AG)","Labour Party","Labour Together","Lucid Theorem","Lähtijät Oy",
    "M&R Strategic Services","M-E-L Research","MAC Research","Market Intelligence Systems (MIS) B.V.","MARKET VISION LLC","MARKETWORTH SLL","Markteffect NL","Masmetrica Research Company SL","Max Planck Institute for EA","McCrindle Research","McMillion Research","MDI Global USA","Media FOCUS Research Ges.m.b.H.","mindline GmbH","MIT","More than Research Group","Morning Light Strategy","MP Ethnic Path","MQO Research","Mr. President","Neoteric Research Services LLP","New Orleans Perspectives","New River Strategies","Nextplora","Niche Markets LC","Nimble Insights MR Private Limited","NinjaTrader","Noble Predictive Insights","North Base Ventures FZ-LLC","Noto Sondaggi Societa' a Responsabilita' Limitata","Obsurvant","Octopus group","ON THE GO","OnePulse","Openfield Creative, Inc.","Opinion Nation Inc.","OpinionWorks","Opinometre","Optimal Workshop Ltd","OutsizedInsights","Panel Inzicht","Panel Sights","Paradigm Sample, LLC._CintX","Paradigm Sample, LLC_Developer","PARK RESEARCH SOLUTIONS LIMITED","Philip L Garland","Philomath","Pivotal Research Inc","plainable GmbH","Plarium Global Ltd.","Plymouth Marine Laboratory Ltd.","PMI","Points Terra LLC","Portland Marketing Analytics","Positly, Inc _ Prod","Praxis Research","Pro Dynamic Research","ProfitWell","Progresso Research","Promark Research","ProQuoAI","Public Pulse Analytics","PwC","Quad/Graphics","Qualtrics [Cint Exchange Trial]","Quantipulse","Quantum Data Quest","R/GA Media Group, Inc","Rain the Growth Agency","Ramp Business Corporation","RealEyes","RealEyes - Cint Exchange","Recon Analytics","Research America","Research COPS","Researchplate","Revolute","Rivel Research Group","RIWI","Russell Research","Salvetti & Llombart S.L. (Digital Insights)","SampPoint","Seattle Children's Hospital","Sensory Analytics, LLC","Shurtape Technologies, LLC","Siena Research Institute","SliceMR",
    "SmithGeiger","Society For Human Resource Management","Sogolytics","Sonder","spark*advocacy","Stanford University - Lab for Social Research","StatWorld Analytics, LLC","Stella & Chewy's","Survey2Connect Private Limited","SurveyUSA","SWG S.P.A.","Syno International","Synqrinus","T&H Research ","Taglia Consulting","Techconsult GmbH","Test - Positly, Inc","TestSet-API_CintX","The Clorox Company","The Home Depot, Inc.","The Meyocks Group Inc.","The University of Melbourne","The Web Opinion","Thinkfield","ThisThat","TOFI","Tracksuit","Training Industry, Inc.","Tree of Insights","Trendecho MR And Tech Solutions Private Limited","Trendence Deutschland","TUDASHBOARD INC","Tufts University","UC - San Diego","Unguess","UsabilityHub Pty Ltd T/As Lyssna","User Sense B.V.","Vernon Research","Vitreous World","Vyacomm Media","Washington Post","We are testers","Weischer Holding Kg","WISERABBIT SP. Z O.O","Woodstream Canada Corporation","XERFI SPECIFIC","Xtreme Nordic AB","YourCareChoice","Zencity","Zillow Group, Inc.","Zinklar","Zk Analytics Ltd","Zogby Analytics",
];
